# Generated by Django 4.0.4 on 2022-08-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_owner_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_owner_operator',
            field=models.BooleanField(),
        ),
    ]
