# Generated by Django 4.0.4 on 2022-08-31 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_is_owner_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_rate',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
