# Generated by Django 4.0.4 on 2022-08-31 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_pay_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pay_rate',
        ),
    ]
