# Generated by Django 4.0.4 on 2022-09-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_pay_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_owner_operator',
            field=models.BooleanField(default=False, verbose_name='trucker status'),
        ),
    ]
