# Generated by Django 4.0.4 on 2022-08-31 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_from', models.CharField(max_length=64)),
                ('place_to', models.CharField(max_length=64)),
                ('distance', models.FloatField(max_length=7)),
                ('income', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date_started', models.DateField(auto_now_add=True)),
                ('date_ended', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
