# Generated by Django 4.0.4 on 2022-08-31 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_ended',
            field=models.DateField(blank=True),
        ),
    ]
