# Generated by Django 4.0.4 on 2022-09-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_date_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
