# Generated by Django 4.1.3 on 2022-11-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='trip',
            name='income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='trip',
            name='place_from',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='trip',
            name='place_to',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
