# Generated by Django 4.1.3 on 2022-11-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_distance_alter_trip_income_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(max_length=7),
        ),
        migrations.AlterField(
            model_name='trip',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='trip',
            name='place_from',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='trip',
            name='place_to',
            field=models.CharField(max_length=64),
        ),
    ]
