# Generated by Django 4.0.4 on 2022-08-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucker_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='truckerprofile',
            name='pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
