# Generated by Django 4.0.4 on 2022-09-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='date_added',
            field=models.DateField(auto_now_add=True, default='2020-08-21'),
            preserve_default=False,
        ),
    ]
